# Generated by Django 2.1 on 2018-08-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bake_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
