# Generated by Django 2.1 on 2018-08-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bake_app', '0004_auto_20180825_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='updated',
        ),
    ]
